service: aws-node-alexa-skill

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:*"
       Resource:
         - "arn:aws:ses:us-east-1:858220449573:identity/*"

functions:
  luckyNumber:
    handler: handler.luckyNumber
    events:
      - alexaSkill
  bookBoarding:
    handler: handler.bookBoarding
    events:
      - alexaSkill

custom:
  browserify:
    presets:
      - es2016

package:
  individually: true
